### ISSUE TITLE
Generating stub produces segfault

### ISSUE THREAD

**Issue by gtamas** [sasezaki/php-extension-stub-generator#8]
Hi

I have a custom PHP extension I'm working on. It's written in C++, using PHP-CPP library.

Tried the following:

`php -d extension=./dist/aspose_php.so ../stub/php-extension-stub-generator/php-extension-stub-generator.phar dump-files aspose-php tmp`

However, this produces an error:

PHP Warning:  Module 'aspose_php' already loaded in Unknown on line 0
Segmentation fault (core dumped)

What am I doing wrong?

I'm using PHP 7.4, running Ubuntu Linux 18.

**Comment by sasezaki** [comment]
Hi @gtamas 

Firstly,

> PHP Warning: Module 'aspose_php' already loaded in Unknown on line 0

So, you don't need `-d extension=./dist/aspose_php.so`.


And, please try `dump` command to get more info.
`php ../stub/php-extension-stub-generator/php-extension-stub-generator.phar dump aspose-php`

I assume something would be output before Segmentation fault.

**Comment by gtamas** [comment]
Sorry, my bad. It's working now.
